# Book settings
title: CPSC 455 
author: Firas Moosvi and Ian McLean
logo: images/logo.jpg
copyright: ""
exclude_patterns: ["LICENSE.md", "README.md"]
only_build_toc_files: true

bibtex_bibfiles:
  - about/citations.bib

latex:
  latex_documents:
    targetname: book.tex
html:
  home_page_in_navbar : true
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  navbar_number_sections : false
  # announcement: "Use this JupyterBook as a <a href='https://github.com/firasm/jupyterbook_course_template' style='color:pink;'>template by clicking here</a>!"  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  # google_analytics_id: UA-11111111 # add your Google Analytics Tracking Code
  comments:
    hypothesis: false
    utterances:
      repo: "UBC-CS/cpsc455"
    dokieli: false
  extra_footer : |
      <div>
      <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/"><img src="https://licensebuttons.net/l/by-nc-sa/3.0/88x31.png"></a>
          All content on this site (unless otherwise specified) is licensed under the <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0 license</a>
      </div>

# launch_buttons:
#   notebook_interface : "jupyterlab"
#   binderhub_url      : "https://mybinder.org"
#   thebe              : true

repository: 
  url          : https://github.com/UBC-CS/cpsc455
  path_to_book : ""
  branch       : main

sphinx:
  config:
    html_show_copyright: false
    html_extra_path: ['files']
    bibtex_reference_style: author_year
    myst_heading_anchors: true
    myst_heading_anchors: 3
    myst_enable_extensions: 
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_image
    - linkify
    - replacements
    - substitution

    myst_substitutions:
      # Instructor information
      INSTRUCTOR: "Dr. Firas Moosvi (he/his/him) and Ian"
      PRONOUNCE: "Fur-az Moose-vee"
      OFFICE: "ICCS 253"
      PHONE: "N/A"

      # Course Information
      COURSE_CODE: "CPSC 455"
      SECTION: "901"
      CREDITS: "3"
      TITLE: "Applied Industry Practices"
      PREREQS: "Pre-reqs: One of CPSC 310, CPEN 321."
      COREQS: "N/A"
      TERM: "2024 Summer Term"
      ROOM: "Online"
      MEETING_TIMES: "Every other Saturday starting May 11th"
      # FORMAT: "Lectures, Labs, Tutorials will all be running in-person."

      # Important Links
      CANVAS_ID: "142514"
      CANVAS_LINK: "https://canvas.ubc.ca/courses/CANVAS_ID"
      ZOOM_LINK: "[Zoom](https://canvas.ubc.ca/courses/CANVAS_ID/external_tools/15408)"
      ANNOUNCEMENTS_LINK: "[Canvas Announcements](https://canvas.ubc.ca/courses/CANVAS_ID/announcements)"
      COURSE_LINK: "https://firas.moosvi.com/courses/cpsc455/2024S/"
      FORUM_LINK: "[Ed Discussion](https://edstem.org/us/join/xyhhmY)"
      TEXTBOOK: "We will not be needing a textbook for this course as you will be provided all the notes you need via the course website and linked materials."
      ANON_FEEDBACK: "[feedback form](https://ubc.ca1.qualtrics.com/?course=cpsc455&term=2024_S)"
      ASSOCIATE_HEAD: "Associate Head [associate.head@fakeemail.ca](mailto:associate.head@fakeemail.ca)"
      ANALYTICS_OPTOUT: "[complete this form](https://ubc.ca1.qualtrics.com/jfe/form/SV_0p6lP4TtNpJn410/?course=cpsc455&term=2024_S)"

      # Withdrawal Dates and Exam Period
      # https://vancouver.calendar.ubc.ca/dates-and-deadlines
      W_DATE_1: "11:59 PDT on January 19, 2024"
      W_DATE_2: "11:59 PDT on March 1, 2024"
      W_DATE_3: "11:59 PDT on March 1, 2024"
      EXAM_PERIOD: "Tuesday April 16th - Saturday, April 27"

      # Course Policies
      GRACE_PERIOD: "48 hour"

      # TA Names
      TA1: "Braeden Fong"
      TA1pronounce: "BRAY-DIN"
      TA2: "Manushree Singhania"
      TA2pronounce: "MA-NU-SHREE"
      TA3: "Minh Anh Nguyen"
      TA3pronounce: "Ming Ang"